#----------------------------------------------------------------------------
#  Copyright (c) 2018 WSO2, Inc. http://www.wso2.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#----------------------------------------------------------------------------
---
  - name: Set rpm_setup_path
    set_fact:
      setup_path: "{{ rpm_setup_path }}"
      java_home: '"/usr/lib64/wso2/wso2is-analytics/5.7.0/jdk/jdk1.8.0_192"'
    when: ansible_os_family == "RedHat"

  - name: Set deb_setup_path
    set_fact:
      setup_path: "{{ deb_setup_path }}"
      java_home: '"/usr/lib/wso2/wso2is-analytics/5.7.0/jdk/jdk1.8.0_192"'
    when: ansible_os_family == "Debian"

  - block:
    - name: Copy the Debian package of WSO2 Identity Server
      copy:
        src: "{{ product_package_location }}/{{ product_archive_deb }}"
        dest: "{{ product_path }}/{{product_archive_deb }}"
        mode: u=rw,g=r,o=r
      when: ansible_os_family == "Debian"

    - name: Copy the RPM package of WSO2 Identity Server
      copy:
        src: "{{ product_package_location  }}/{{ product_archive_rpm  }}"
        dest: "{{ product_path  }}/{{ product_archive_rpm  }}"
        mode: u=rw,g=r,o=r
      when: ansible_os_family == "RedHat"

    - name: Install a .deb package
      apt:
        deb: "{{ product_path  }}/{{ product_archive_deb  }}"
      when: ansible_os_family == "Debian"

    - name: Install a .rpm package
      yum:
        name: "{{ product_path  }}/{{ product_archive_rpm  }}"
      when: ansible_os_family == "RedHat"

    - name: "Copy JDBC Driver"
      copy:
       src: "files/{{ jdbc_driver }}"
       dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/lib"

    - name: "Copy deployment.yaml"
      template:
        src: "carbon-home/conf/worker/deployment.yaml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/conf/worker/deployment.yaml"

    - name: "Copy carbon.sh"
      template:
        src: "carbon-home/wso2/worker/bin/carbon.sh.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/wso2/worker/bin/carbon.sh"

    - name: Change the owner of WSO2 directory
      file:
        path: "{{ setup_path }}"
        state: directory
        recurse: true
        owner: "{{ wso2_user }}"
        group: "{{ wso2_group }}"
        mode: 0755

    when: "(inventory_hostname in groups['is-analytics'])"
    become: true
    become_method: sudo
    become_user: root

# Enable customization by uncommenting the following and adding the changes to the custom.yml
      # - import_tasks: custom.yml

  - block:
    - name: Copy WSO2 IS Analytics worker service file
      template:
        src: wso2is-analytics-worker.service.j2
        dest: /etc/systemd/system/wso2is-analytics-worker.service

    - name: Reload systemctl daemon
      command: systemctl daemon-reload

    - name: Start wso2is-analytics-worker as a service
      command: systemctl start wso2is-analytics-worker.service

    become: true
    become_user: root
